name: 'Create GitHub Releases'

on: 
  workflow_call:

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        run: gh release create ${{ github.ref }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

